#!/usr/bin/env bash
DIR=$(pwd)

# First clean .vim and .vimrc
rm -rv ~/.vim/
rm -rv ~/.vimrc
    
# VIM
ln -s $DIR/.vim ~/
ln -s $DIR/.vimrc ~/

# Install commandt
./.vim/installBundles
cd ./.vim/bundle/Command-T/
rake make

# install syntax for pyton
sudo apt-get install python-pip
pip install flake8
