#!/usr/bin/env bash
DIR=$(pwd)

# First clean .vim and .vimrc
rm -rv ~/.vim/
rm -rv ~/.vimrc
    
# VIM
ln -s $DIR/.vim ~/
ln -s $DIR/.vimrc ~/

# Install commandt
./.vim/update_bundles
cd ./.vim/bundle/Command-T/
rake make

# install syntax for pyton
pip install flake8

# install syntax for js
sudo apt-get install npm
sudo npm install jshint -g
