#!/usr/bin/env ruby

git_bundles = %w{
  git://github.com/Lokaltog/vim-powerline.git
  git://github.com/scrooloose/nerdtree.git

  git://github.com/tpope/vim-fugitive.git
  git://github.com/tpope/vim-repeat.git
  git://github.com/tpope/vim-surround.git

  git://github.com/vim-scripts/buftabs.git
  git://github.com/vim-scripts/CmdlineComplete.git
  git://github.com/abudden/TagHighlight.git
  git://github.com/majutsushi/tagbar.git

  git://github.com/Lokaltog/vim-easymotion.git

  git://github.com/gerw/vim-latex-suite.git

  git://github.com/wincent/Command-T.git

  git://github.com/vim-scripts/vimwiki.git

  git://github.com/samsonw/vim-task.git

  git://github.com/vim-scripts/AutoComplPop.git

  git://github.com/scrooloose/syntastic.git
  git://github.com/nvie/vim-flake8.git

  git://github.com/djoshea/vim-matlab-fold.git

  git://github.com/vim-scripts/jsbeautify.git
  git://github.com/kchmck/vim-coffee-script.git
  git://github.com/digitaltoad/vim-jade.git

  git clone git://github.com/mileszs/ack.vim.git
  git://github.com/kien/ctrlp.vim.git

  git://github.com/vim-scripts/EnhCommentify.vim.git

  git://github.com/garbas/vim-snipmate.git
  git://github.com/honza/snipmate-snippets.git
  git://github.com/MarcWeber/vim-addon-mw-utils.git
  git://github.com/tomtom/tlib_vim.git
  git://github.com/tomtom/tcommand_vim.git
  git://github.com/tpope/vim-markdown.git
}

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.rm_rf(bundles_dir)
FileUtils.mkdir(bundles_dir)
FileUtils.cd(bundles_dir)

git_bundles.each do |url|
  puts url
  `git clone -q #{url}`
end

# Dir["*/.git"].each {|f| FileUtils.rm_rf(f) }
